# Site settings
title: Sasha Prokhorenko
header-img: img/main-bg.png
email: djminikin@gmail.com
copyright_name: Sasha Prokhorenko
description: "iOS Software Engineer & IoT adept."
baseurl: ""
url: "http://minikin.me"
logo: "/img/main-bg.png"
twitter_username: minikin
github_username:  minikin
email_username:  djminikin@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap, jemoji, jekyll-seo-tag]